# Generated by Django 4.0.6 on 2022-08-26 02:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0003_alter_cliente_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='created',
        ),
    ]
