# Generated by Django 4.0.6 on 2022-09-04 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil_usuario',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='perfil_imagen'),
        ),
    ]
