# Generated by Django 4.0.6 on 2022-09-05 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0002_alter_perfil_usuario_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil_usuario',
            name='direccion',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='perfil_usuario',
            name='telefono',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
