# Generated by Django 4.0.6 on 2022-08-07 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categorias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('id_producto', models.IntegerField()),
                ('clasificacion', models.CharField(max_length=50)),
            ],
        ),
    ]
