# Generated by Django 3.0.4 on 2022-08-09 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categorias', '0002_remove_categorias_id_producto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categorias',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
