# Generated by Django 4.0.6 on 2022-08-20 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categorias', '0003_auto_20220809_0904'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categorias',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
